name: Secure Code Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  secure-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run secure code scanner
        run: |
          python scanner.py \
            --mode ci \
            --rules rules.json \
            --fail-level HIGH \
            .
